# Generated by Django 6.0.3 on 2026-03-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('read_time', models.CharField(max_length=50)),
                ('category_color', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('author', models.CharField(default='Zahed Hasan Rabbi', max_length=100)),
                ('author_role', models.CharField(default='Engineering Manager', max_length=100)),
                ('author_bio', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('is_current', models.BooleanField(default=False)),
                ('highlights', models.JSONField()),
                ('tech', models.JSONField()),
                ('company_logo', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('my_role', models.CharField(max_length=100)),
                ('team_size', models.CharField(max_length=50)),
                ('impact_metric', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech', models.JSONField()),
                ('gradient', models.CharField(max_length=200)),
                ('syscomatic_link', models.URLField(blank=True, max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('client_background', models.TextField(blank=True)),
                ('challenge', models.TextField(blank=True)),
                ('approach_solution', models.TextField(blank=True)),
                ('key_features', models.JSONField(blank=True, default=list)),
                ('impact_detailed', models.JSONField(blank=True, default=list)),
                ('client_testimonial', models.TextField(blank=True)),
                ('client_testimonial_author', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('leadership', 'Leadership'), ('technical', 'Technical')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=5)),
                ('initials', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=20)),
                ('video_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
